config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { omniauth_callbacks: :callbacks }
  root "games#index"

  resources :critics
  resources :involved_companies
  resources :games do
    resources :critics
    post "/add_developer_game", to: "games#add_developer"
    # /games/:id/add_genre
    post "add_genre", on: :member
    # /games/:id/remove_genre
    delete "remove_genre", on: :member

    # /games/:id/add_platform
    post "add_platform", on: :member
    # /games/:id/remove_platform
    delete "remove_platform", on: :member

    # /games/:id/add_developer
    post "add_developer", on: :member

    # /games/:id/remove_developer
    delete "remove_developer", on: :member

    # /games/:id/add_publisher
    post "add_publisher", on: :member

    # /games/:id/remove_publisher
    delete "remove_publisher", on: :member
  end
  resources :platforms
  resources :genres
  resources :companies do
    resources :critics
  end
  # resources :users, only: :new

  # get "/login", to: "sessions#new"
  # post "/sessions", to: "sessions#create"
  # delete "/sessions", to: "sessions#destroy"

  # user_url
  get "/profile", to: "users#show", as: "user"
  # get "/profile", to: "users#edit"
  # patch "/profile", to: "users#update"
  # post "/profile", to: "users#create"

  # Omniauth
  # post '/auth/github', to: 'github_login'
  # get 'auth/github/callback', to: 'sessions#create'

end

app/models/game.rb
class Game < ApplicationRecord
    # Attached
    has_one_attached :cover
    # Validations
    validates :name, :category, presence: true
    validates :name, uniqueness: true
    validates :rating,
              numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 },
              allow_nil: true
    # Validates parent is included in the list of main_game's only if the category is not main_game
    validates :parent, inclusion: { in: proc { Game.main_game },
                                    message: "is not a valid game" },
                       unless: proc { main_game? || category.nil? }
    # Validates that parent is nil when the game is a main_game
    validates :parent, absence: true, if: proc { main_game? }
  
    # Enums
    enum category: { main_game: 0, expansion: 1 }
  
    # Associations
    belongs_to :parent, class_name: "Game", optional: true
    has_many :expansions, class_name: "Game",
                          foreign_key: "parent_id",
                          dependent: :nullify,
                          inverse_of: "parent"
  
    has_many :involved_companies, dependent: :destroy
    has_many :companies, through: :involved_companies
  
    has_and_belongs_to_many :genres
    has_and_belongs_to_many :platforms
  
    has_many :received_critics, class_name: "Critic", 
    as: :criticable, 
    dependent: :destroy
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  def index
    @games = Game.all
  end

  # GET /games/:id
  def show
    @game = Game.find(params[:id])
  end

  # GET /games/new
  def new
    @game = Game.new
    @main_games = Game.main_game
  end

  # GET /games/:id/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  def create
    @game = Game.new(game_params)

    if @game.save
      redirect_to @game
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /games/:id
  def update
    @game = Game.find(params[:id])

    if @game.update(game_params)
      redirect_to @game
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /games/:id
  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to games_path, status: :see_other
  end

  # Custom Routes

  # POST /games/:id/add_genre
  def add_genre
    game = Game.find(params[:id])
    genre = Genre.find(params[:genre_id])

    game.genres << genre
    redirect_to game
  end

  # DELETE /games/:id/remove_genre
  def remove_genre
    game = Game.find(params[:id])
    genre = Genre.find(params[:genre_id])

    game.genres.delete(genre)
    redirect_to game, status: :see_other
  end

  # POST /games/:id/add_platform
  def add_platform
    game = Game.find(params[:id])
    platform = Platform.find(params[:platform_id])

    game.platforms << platform
    redirect_to game
  end

  # POST /games/:id/add_developer
  def add_developer
    game = Game.find(params[:id])
    developer = InvolvedCompany.find(params[:company_id])
    
    game.developer << developer
    redirect_to game
  end
  
  # DELETE /games/:id/remove_developer
  def remove_developer
   game = Game.find(params[:id])
   developer = InvolvedCompany.find(params[:company_id])
 
   game.developer.delete(developer)
   redirect_to game, status: :see_other
 end

  def add_developer
    game = Game.find(params[:id])
    InvolvedCompany.create(game_id: params[:game_id], company_id: params[:company_id], developer: true, publisher: false)
    redirect_to game
  end

  private

  # Only allow a list of trusted parameters through.
  def game_params
    params.require(:game).permit(:name, :summary, :release_date, :category, :rating, :parent_id, :cover)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block"%>
    <%= form.text_field :name, placeholder: "Magic Game"%>
    <%=errors_for(game, :name)%>
  </div>

  <div>
    <%= form.label :summary, style: "display: block" %>
    <%= form.text_area :summary, placeholder: "About game SA..." %>
    <%=errors_for(game, :summary)%>
  </div>

  <div>
    <%= form.label :release_date, style: "display: block" %>
    <%= form.text_field :release_date %>
    <%=errors_for(game, :release_date)%>
  </div>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.number_field :rating, step: 0.1 %>
    <%=errors_for(game, :rating)%>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.select :category, Game.categories.keys, { prompt: true } %>
    <%=errors_for(game, :category) %>
  </div>


  <div>
    <%= form.label :parent_id, style: "display: block" %>
    <%= form.collection_select :parent_id, Game.main_game, :id, :name, { include_blank: "Please select" } %>
    <%=errors_for(game, :parent_id)%>
  </div>

  <div><%= form.label :cover%> </div>
  <div><%= form.file_field :cover%></div>
  <div><%= image_tag(game.cover) if game.cover.attached?%></div>

  <div><%= form.submit %></div>
    
   <div> <%= link_to "Back", games_path%></div>
  
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">
  <p>
    <strong>Name:</strong>
    <%= game.name %>
  </p>

  <p>
    <strong>Summary:</strong>
    <%= game.summary %>
  </p>

  <p>
    <strong>Release date:</strong>
    <%= game.release_date %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= game.category %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= game.rating %>
  </p>

</div>

app/views/games/edit.html.erb
<section class="section">
<section class="container">

<h1>Edit Game</h1>

<%= render "form", game: @game %>

</section>
</section>

app/views/games/index.html.erb
<section class="section">
  <section class="container">

<p style="color: green"><%= notice %></p>

<h1 class="heading">Games</h1>
<%= link_to "New game", new_game_path, class: " button button--primary fit-content mg-1" %>

<%# <div id="games"> %>
       

  <% @games.each do |game| %>
  <section class="card py-3">
    <div class="card_image">
      <% if game.cover.attached? %>
      <div class=img-about><%= image_tag game.cover%></div>
      <% end %>
      </div>
      <p><%= link_to game.name, game %></p>
      <p><%= game.summary %></p>
      <p><%= game.release_date %></p>
      <p><%= game.category %></p>
      <p><%= game.rating %></p>
      <p><%= game.received_critics.size%> Critics</p>
    <div class="card_icon">
      <%= link_to image_tag('Edit.png',:alt => 'edit'), edit_game_path(game) %>
      <%= link_to image_tag('Delet.png',:alt => 'destroy'), game, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
    </div>

  </section> 
  <% end %>
 

</section>
</section>

app/views/games/new.html.erb
<section class="section">
  <section class="container">

<h1>New game</h1>

<%= render "form", game: @game %>

</section>
</section>

app/views/games/show.html.erb
<section class="section">
  <section class="container">
    <h1 class="heading">Game details</h1>
    <div class="flex flex-column gap-4 content-lg">
    <% if @game.cover.attached? %> 
      <div>
      <%= image_tag @game.cover, alt: "Image to #{@game.name}"%> 
      </div>
      <% else %> 
      <div>
     <%= image_tag "empty.png", alt: "Empty image", class: "img-game" %> 
     </div>
    <% end%>
      <div>
        <%= @game.name %>
      </div>

      <div>
        <%= @game.release_date.year %>
      </div>

      <div>
        <%= @game.rating %>
      </div>

    <h1 class="heading">Game details</h1>

      <div>
        <%= @game.summary %>
      </div>

      <div>
        <strong>Genres:</strong>
        <ul>
          <% @game.genres.each do |genre| %>
          <li><%= genre.name%> | <%= link_to 'remove', remove_genre_game_path(@game, genre_id: genre.id), data: { turbo_method: :delete }  %></li>
          <% end %>
        </ul>
      </div>

      <div>
        <strong>Platforms:</strong>
        <ul>
          <% @game.platforms.each do |platform| %>
          <li><%= platform.name%> | <%= link_to 'remove', remove_platform_game_path(@game, platform_id: platform.id), data: { turbo_method: :delete }  %></li>
          <% end %>
        </ul>
        <%# <strong>Developers:</strong> %>
        <%# <% @game.involved_companies.each do |developer| %> 
          <%# <%= developer.name %>  
          <%# <% end %> 
      </div>
        <strong>Add relations:</strong>
      <div>
        <ul>
          <li>
            <%= form_with(url: add_genre_game_path(@game), class: "flex flex-column gap-4 flex-row") do |form| %>
              <div class="flex gap-4">
                <div class="select">
                  <%= form.collection_select :genre_id, (Genre.all - @game.genres), :id, :name, { prompt: true }, { class: "select__input" } %>
                </div>
              </div>
              <%= form.submit "Add genre", class: "button button--primary fit-content" %>
            <% end %>
          </li>
          </ul>
          <ul>
          <li>
            <%= form_with(url: add_platform_game_path(@game), class: "flex flex-column gap-4 flex-row") do |form| %>
              <div class="flex gap-4">
                <div class="select">
                  <%= form.collection_select :platform_id, (Platform.all - @game.platforms), :id, :name, { prompt: true }, { class: "select__input" } %>
                </div>
              </div>
              <%= form.submit "Add platform", class: "button button--primary fit-content" %>
            <% end %>
          </li>
        </ul>
      </div>

      <div>

      <strong>Developers:</strong>

       <%= form_with(url: game_add_developer_game_path(@game),class: "flex flex-column gap-4 flex-row") do |form|%>
          <div class="flex gap-4">
            <div class="select"> 
          <%= form.collection_select :company_id, Company.all, :id, :name , { prompt: true }, { class: "select__input" }%>
            </div>
          </div>
          <%= form.submit "Add developer",class: "button button--primary fit-content"%>
      <% end %>
      </div>


      <div>
        <%= link_to 'Edit', edit_game_path(@game) %> |
        <%= link_to 'Back', games_path %>
      </div>
    </div>

<section class="section">
<section class="container">
  </div>
</div>
<div class="container">
 <%= render "critics/form", critic: Critic.new, criticable: @game%>


  <% @game.received_critics.each do |critic| %>
    <%= render "critics/critic", critic: critic %>
  <% end %>
  </div>
</section>
</section>