config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { omniauth_callbacks: :callbacks }
  root "games#index"

  resources :critics
  resources :involved_companies
  resources :games do
    resources :critics
    post "/add_developer_game", to: "games#add_developer"
    # /games/:id/add_genre
    post "add_genre", on: :member
    # /games/:id/remove_genre
    delete "remove_genre", on: :member

    # /games/:id/add_platform
    post "add_platform", on: :member
    # /games/:id/remove_platform
    delete "remove_platform", on: :member

    # /games/:id/add_developer
    post "add_developer", on: :member

    # /games/:id/remove_developer
    delete "remove_developer", on: :member

    # /games/:id/add_publisher
    post "add_publisher", on: :member

    # /games/:id/remove_publisher
    delete "remove_publisher", on: :member
  end
  resources :platforms
  resources :genres
  resources :companies do
    resources :critics
  end
  # resources :users, only: :new

  # get "/login", to: "sessions#new"
  # post "/sessions", to: "sessions#create"
  # delete "/sessions", to: "sessions#destroy"

  # user_url
  get "/profile", to: "users#show", as: "user"
  # get "/profile", to: "users#edit"
  # patch "/profile", to: "users#update"
  # post "/profile", to: "users#create"

  # Omniauth
  # post '/auth/github', to: 'github_login'
  # get 'auth/github/callback', to: 'sessions#create'

end

app/models/company.rb
class Company < ApplicationRecord
    # Attached
    has_one_attached :cover
    validates :name, presence: true, uniqueness: true

    # Associations
    has_many :involved_companies, dependent: :destroy
    has_many :games, through: :involved_companies, counter_cache: true
    has_many :received_critics, class_name: "Critic", 
    as: :criticable, 
    dependent: :destroy
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  def index
    @companies = Company.all
  end

  # GET /companies/:id
  def show
    @company = Company.find(params[:id])
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/:id/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to @company
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /companies/:id
  def update
    @company = Company.find(params[:id])

    if @company.update(company_params)
      redirect_to @company
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /companies/:id
  def destroy
    @company = Company.find(params[:id])
    @company.destroy
    redirect_to companies_path, status: :see_other
  end

  private

  # Only allow a list of trusted parameters through.
  def company_params
    params.require(:company).permit(:name, :description, :start_date, :country, :cover)
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.erb
<section class="section">
  <div class="container">

<div id="<%= dom_id company %>">
  <% if company.cover.attached? %> 
    <div>
      <%= image_tag company.cover, alt: "Image to #{company.name}" %> 
    </div>
  <% else %> 
    <div>
    <%= image_tag "empty.png", alt: "Empty image", class: "img-company" %> 
    </div>
  <% end%>

  <p>
    <strong>
    <%= company.name %>
    </strong>
  </p>
  <p>
    <%= company.start_date.year %> - <%= company.country %>
  </p>

  <%= link_to "Company Details", company_path(@company) %>
  <%= link_to "Critics #{company.received_critics.size}" , "#"%>  

  <p>
    <%# <strong>Description:</strong> %>
    <%= company.description %>
  </p>
</div>

<br/>
  <h3>Games <%=company.games.count%> </h3>

  <% company.games.each do |game| %>
  <% if game.cover.attached? %> 
    <div>
      <%= image_tag game.cover, alt: "Image to #{game.name}" %> 
    </div>
  <% else %> 
    <div>
    <%= image_tag "empty.png", alt: "Empty image", class: "img-game" %> 
    </div>
  <% end%>
    <%= render "games/game", game: game %><br/>
  <% end %>

 <hr>
  <%= render "critics/form", critic: Critic.new, criticable: @company%>
  <% @company.received_critics.each do |critic| %>
    <%= render "critics/critic", critic: critic %>
  <% end %>

  </div>
</section>

app/views/companies/_form.html.erb
<%= form_with(model: company) do |form| %>
  <% if company.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :country, style: "display: block" %>
    <%= form.text_field :country %>
  </div>

  <div>
  <%= form.label :cover%> </div>
  <%= form.file_field :cover%>
  <%= image_tag(company.cover) if company.cover.attached?%>
  </div>

  <br/>
    <%= form.submit %>
  
<% end %>

app/views/companies/edit.html.erb
<section class="section">
  <section class="container">

<h1>Edit company</h1>

<%= render "form", company: @company %>

<br>

<div>
  <%= link_to "Show", @company %> |
  <%= link_to "Back", companies_path %>
</div>

</section>
</section>

app/views/companies/index.html.erb
<section class="section">
  <section class="container">
<h1 class="heading">Companies</h1>

<%= link_to "New company", new_company_path, class: "button button--primary fit-content mg-1" %>


  <% @companies.each do |company| %>
  <section class="card py-3">
  
    <div class="card_image">
      <% if company.cover.attached? %>  
        <div class=img-about><%= image_tag company.cover %></div>
      <% end %> 
    </div>
    <div><%= link_to company.name,company %></div>
    <% if company.start_date %>
    <p> <%= company.start_date.strftime("%Y") %>-<%=company.country %></p>
    <% end %>
    <div><%= company.description %></div>
    <p><%= company.games.count %> Games </p>
    <div class="card_icon">
    <p><%= link_to image_tag('Edit.png',:alt => 'edit'), edit_company_path(company) %></p>
    <p><%= link_to image_tag('Delet.png',:alt => 'destroy'), company, data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
       } %></p>
    </div>
    </section>
  <% end %>
</section>
</section>

app/views/companies/new.html.erb
<section class="section">
  <section class="container">

<h1>New company</h1>

<%= render "form", company: @company %>

<br>

<div>
  <%= link_to "Back", companies_path %>
</div>

</section>
</section>

app/views/companies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @company %>

<div>
  
  <%= link_to "Back", companies_path %>

</div>