config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { omniauth_callbacks: :callbacks }
  root "games#index"

  resources :critics
  resources :involved_companies
  resources :games do
    resources :critics
    post "/add_developer_game", to: "games#add_developer"
    # /games/:id/add_genre
    post "add_genre", on: :member
    # /games/:id/remove_genre
    delete "remove_genre", on: :member

    # /games/:id/add_platform
    post "add_platform", on: :member
    # /games/:id/remove_platform
    delete "remove_platform", on: :member

    # /games/:id/add_developer
    post "add_developer", on: :member

    # /games/:id/remove_developer
    delete "remove_developer", on: :member

    # /games/:id/add_publisher
    post "add_publisher", on: :member

    # /games/:id/remove_publisher
    delete "remove_publisher", on: :member
  end
  resources :platforms
  resources :genres
  resources :companies do
    resources :critics
  end
  # resources :users, only: :new

  # get "/login", to: "sessions#new"
  # post "/sessions", to: "sessions#create"
  # delete "/sessions", to: "sessions#destroy"

  # user_url
  get "/profile", to: "users#show", as: "user"
  # get "/profile", to: "users#edit"
  # patch "/profile", to: "users#update"
  # post "/profile", to: "users#create"

  # Omniauth
  # post '/auth/github', to: 'github_login'
  # get 'auth/github/callback', to: 'sessions#create'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Critics</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header class="header">
    <div class="container navbar">
      <a href="/games" class="logo">
        <img
          src="/images/logo.png"
          alt="Critics"
          height="40"
        />
      </a>
      <nav>
        <ul class="navbar-links" role="list">
          <%# <li><%= link_to 'Users', users_path, class: "link" %>
          <li><%= link_to 'Games', games_path, class: "link" %></li>
          <li><%= link_to 'Companies', companies_path, class: "link" %></li>
          <%# <li><%= link_to 'Genres', genres_path, class: "link" %>
          <%# <li><%= link_to 'Platforms', platforms_path, class: "link" %>
          <%# <li><%= link_to 'Involved Companies', involved_companies_path, class: "link" %>
          <%# <li><%= link_to 'Critics', critics_path, class: "ink" %>
        </ul>
      </nav>
      
        <%# <% if current_user %> 
          <%# <p>Welcome, <%= current_user.username %>
          <%# <%= link_to "Logout", sessions_path, data: { turbo_method: :delete } %> 
        <%# <% else %> 
          <%# <%= link_to 'Create account', new_user_path %> 
          <%# <%= link_to 'Login', login_path %>
        <%# <% end %> 
      
      <%# Solo si estoy logueado metodo Logout%>
      <%# o estoy logueado Sign in && Sign up%>
      <div><% if user_signed_in? %></div>
      <%= link_to "Edit profile", edit_user_registration_path %>
      <%= button_to "Logout", destroy_user_session_path, method: :delete, data: { turbo: false }, class: "button button--primary fit-content"%>
      <% else %>
      <%= link_to "Sign in", new_user_session_path %>
      <%= link_to "Sign up", new_user_registration_path %>
      <% end %>
      <%= image_tag("/images/menu.svg", class: "navbar__menu-icon") %>
      <%= image_tag("/images/close.svg", class: "navbar__menu-icon-close") %>
    </div>

  </header>
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>

    <footer class="footer">
      <div class="footer__content">
        <p>Build with ♥ by</p> 
      
        <div class="footer__students">
          <a href="https://www.linkedin.com">
            <div class="footer__students-tag">
            <span class="ml-4 fill-current h-4 w-4 text-red-400">
              <%= image_tag("/images/linkedIn-logo.png") %>
            </span>
            <span class="secondary-500">Sebastian Terleira</span>
            </div>
          </a>

          <a href="https://www.linkedin.com">
            <div class="footer__students-tag">
              <span class="ml-4 fill-current h-4 w-4 text-red-400">
                <%= image_tag('/images/linkedIn-logo.png') %>
              </span>
              <span class="secondary-500">Olenka Sanchez</span>
            </div>
          </a>

          <a href="https://www.linkedin.com">
            <div class="footer__students-tag">
            <span class="ml-4 fill-current h-4 w-4 text-red-400">
              <%= image_tag("/images/linkedIn-logo.png") %>
            </span>
            <span class="secondary-500">Tita Ruiz</span>
            </div>
          </a>

          <a href="https://www.linkedin.com">
            <div class="footer__students-tag">
            <span class="ml-4 fill-current h-4 w-4 text-red-400">
              <%= image_tag("/images/linkedIn-logo.png") %>
            </span>
            <span class="secondary-500">Elias Mesones</span>
            </div>
          </a>
        </div>
      </div>
    </footer>
  </body>
</html>